package main

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"os"
	"sync"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"
	_ "github.com/lib/pq"
	_ "github.com/pacheco/go-enrich-demo/enrichment-api/docs" // This will be generated by swag init
	"github.com/pacheco/go-enrich-demo/enrichment-api/models"
	httpSwagger "github.com/swaggo/http-swagger"
)

var db *sql.DB

// @title Enrichment API
// @version 1.0
// @description This is a sample enrichment service.
// @host localhost:8080
// @BasePath /
func main() {
	var err error
	connStr := os.Getenv("DATABASE_URL")
	if connStr == "" {
		connStr = "postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable"
	}
	db, err = sql.Open("postgres", connStr)
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()

	r := chi.NewRouter()
	r.Use(middleware.Logger)

	r.Get("/enrichment", handleEnrichment)
	r.Get("/swagger/*", httpSwagger.WrapHandler)

	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}
	log.Printf("Starting enrichment-api on port %s", port)
	http.ListenAndServe(":"+port, r)
}

// handleEnrichment godoc
// @Summary Enrich customer data
// @Description Get address, pii and suggestions for a customer
// @Accept  json
// @Produce  json
// @Param customer_code query string true "Customer Code"
// @Success 200 {object} models.EnrichmentResponse
// @Router /enrichment [get]
func handleEnrichment(w http.ResponseWriter, r *http.Request) {
	startTime := time.Now()
	customerCode := r.URL.Query().Get("customer_code")
	if customerCode == "" {
		http.Error(w, "customer_code is required", http.StatusBadRequest)
		return
	}

	var resp models.EnrichmentResponse
	var wg sync.WaitGroup

	// 3 concurrent tasks
	wg.Add(3)

	// 1. Get Address from DB
	go func() {
		defer wg.Done()
		addr, err := getAddress(customerCode)
		if err != nil {
			log.Printf("Error getting address: %v", err)
			// Fallback: leave as nil
			return
		}
		resp.Address = addr
	}()

	// 2. Get PII from pii-api
	go func() {
		defer wg.Done()
		piiData, err := getPii(customerCode)
		if err != nil {
			log.Printf("Error getting PII: %v", err)
			return
		}
		resp.Pii = piiData
	}()

	// 3. Get Suggestions from suggestion-api
	go func() {
		defer wg.Done()
		suggestions, err := getSuggestions(customerCode)
		if err != nil {
			log.Printf("Error getting suggestions: %v", err)
			resp.Suggestions = []models.Suggestion{} // Ensure empty array not nil
			return
		}
		resp.Suggestions = suggestions
	}()

	wg.Wait()

	elapsed := time.Since(startTime)
	resp.Metadata = &models.Metadata{
		ProcessingTime: elapsed.String(),
	}

	// Ensure suggestions is not nil if it wasn't set (though we handle it above)
	if resp.Suggestions == nil {
		resp.Suggestions = []models.Suggestion{}
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(resp)
}

func getAddress(customerCode string) (*models.Address, error) {
	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
	defer cancel()

	var addr models.Address
	err := db.QueryRowContext(ctx, "SELECT street, number, city, state, country FROM addresses WHERE customer_code = $1", customerCode).Scan(
		&addr.Street, &addr.Number, &addr.City, &addr.State, &addr.Country,
	)
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, nil // Not found is not an error, just no data
		}
		return nil, err
	}
	return &addr, nil
}

func getPii(customerCode string) (*models.Pii, error) {
	url := os.Getenv("PII_API_URL")
	if url == "" {
		url = "http://localhost:8081/pii"
	}

	client := http.Client{
		Timeout: 2 * time.Second, // Timeout requirement
	}

	reqUrl := fmt.Sprintf("%s?customer_code=%s", url, customerCode)
	req, _ := http.NewRequest("GET", reqUrl, nil)

	res, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	defer res.Body.Close()

	if res.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("status code: %d", res.StatusCode)
	}

	var pii models.Pii
	if err := json.NewDecoder(res.Body).Decode(&pii); err != nil {
		if err.Error() == "EOF" {
			return nil, nil
		}
		return nil, err
	}
	return &pii, nil
}

func getSuggestions(customerCode string) ([]models.Suggestion, error) {
	url := os.Getenv("SUGGESTION_API_URL")
	if url == "" {
		url = "http://localhost:8082/suggestions"
	}

	client := http.Client{
		Timeout: 2 * time.Second,
	}

	reqUrl := fmt.Sprintf("%s?customer_code=%s", url, customerCode)
	req, _ := http.NewRequest("GET", reqUrl, nil)

	res, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	defer res.Body.Close()

	if res.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("status code: %d", res.StatusCode)
	}

	var suggestions []models.Suggestion
	if err := json.NewDecoder(res.Body).Decode(&suggestions); err != nil {
		return nil, err
	}
	return suggestions, nil
}
